# Build stage
FROM golang:alpine3.23 AS builder

WORKDIR /app

COPY go.mod go.sum .
RUN go mod download

COPY . .

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

# Build
RUN go build -o blc_server ./blockchain_server



# Final stage
FROM alpine:3.21

RUN addgroup -S srvgrp && adduser -S srvusr -G srvgrp

WORKDIR /server

COPY --from=builder /app/blc_server .

EXPOSE 5000

USER srvusr

ENTRYPOINT ["./blc_server"]